name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup ROS2 Humble
      uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: humble
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-colcon-common-extensions \
          python3-rosdep \
          python3-vcstool \
          libeigen3-dev \
          libgtest-dev \
          ros-humble-gazebo-ros-pkgs \
          ros-humble-navigation2 \
          ros-humble-moveit \
          ros-humble-controller-manager \
          ros-humble-hardware-interface
    
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest coverage psutil pyyaml
    
    - name: Initialize rosdep
      run: |
        sudo rosdep init || true
        rosdep update
    
    - name: Install package dependencies
      run: |
        rosdep install --from-paths src --ignore-src -r -y
    
    - name: Build workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --symlink-install \
          --cmake-args -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    
    - name: Source workspace
      run: |
        source install/setup.bash
    
    - name: Run tests
      run: |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        colcon test --return-code-on-test-failure
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          log/
          build/*/test_results/
    
    - name: Check for test failures
      run: |
        source /opt/ros/humble/setup.bash
        colcon test-result --verbose

  lint:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup ROS2 Humble
      uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: humble
    
    - name: Install linting tools
      run: |
        sudo apt update
        sudo apt install -y \
          python3-flake8 \
          python3-pytest \
          ros-humble-ament-lint
    
    - name: Run linting
      run: |
        source /opt/ros/humble/setup.bash
        ament_flake8 src/
        ament_cpplint src/
        ament_xmllint src/

  docker-build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: |
        docker build -f docker/Dockerfile -t ros2_foundation:ci .
    
    - name: Test Docker container
      run: |
        docker run --rm ros2_foundation:ci /bin/bash -c "
          cd /workspace &&
          colcon build --symlink-install &&
          source install/setup.bash &&
          ros2 pkg list | grep foundation
        "
